pipeline {
    agent any

    parameters {
        string(
            name: 'NAME',
            defaultValue: 'Mohan',
            description: 'Enter the name'
        )
    }

    tools {
        jdk 'JDK-21'
        maven 'Maven-3.9.16'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Mohanchandra7/jenkins-html-demo.git'

                echo 'Code downloaded from GitHub'
            }
        }

        stage('Maven Goals') {
            steps {
                bat 'mvn clean package'
            }
        }

        stage('HTML') {
            steps {
                echo "Creating HTML for ${params.NAME}"

                bat """
                (
                    echo ^<!DOCTYPE html^>
                    echo ^<html^>
                    echo ^<head^>
                    echo ^<title^>Jenkins HTML Page^</title^>
                    echo ^</head^>
                    echo ^<body^>
                    echo ^<h1^>Hello ${params.NAME}^!^</h1^>
                    echo ^<p^>This page was generated by Jenkins.^</p^>
                    echo ^</body^>
                    echo ^</html^>
                ) > output.html

                echo HTML file created successfully.
                type output.html
                """
            }
        }

        stage('Ansible') {
            steps {
                echo 'Starting Ansible deployment...'

                bat 'wsl -d Ubuntu ansible-playbook /mnt/c/ProgramData/Jenkins/.jenkins/workspace/jenkins-html-demo/deploy.yml'

                echo 'Ansible deployment completed.'
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: 'output.html', fingerprint: true
        }
    }
}
